

import tkinter as tk
from tkinter import filedialog, messagebox
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from PIL import Image, ImageTk
import os

# ----------------------- Generate Admit Card -----------------------
def generate_admit_card():
    name = name_var.get()
    roll = roll_var.get()
    course = course_var.get()
    date = date_var.get()
    center = center_var.get()
    
    if not all([name, roll, course, date, center, photo_path.get()]):
        messagebox.showerror("Error", "Please fill all fields and upload a photo")
        return

    os.makedirs("admit_cards", exist_ok=True)
    filename = os.path.join("admit_cards", f"AdmitCard_{roll}.pdf")

    c = canvas.Canvas(filename, pagesize=A4)
    width, height = A4

    # PDF Title
    c.setFont("Helvetica-Bold", 20)
    c.drawCentredString(width / 2, height - 80, "EXAMINATION ADMIT CARD")

    # Student Details
    c.setFont("Helvetica", 12)
    c.drawString(100, height - 140, f"Name: {name}")
    c.drawString(100, height - 160, f"Roll No: {roll}")
    c.drawString(100, height - 180, f"Course: {course}")
    c.drawString(100, height - 200, f"Exam Date: {date}")
    c.drawString(100, height - 220, f"Exam Center: {center}")

    # Add Photo
    try:
        c.drawImage(photo_path.get(), width - 200, height - 250, 80, 100)
    except:
        messagebox.showwarning("Warning", "Unable to load photo in PDF")

    c.setFont("Helvetica-Oblique", 10)
    c.drawCentredString(width / 2, 50, "Generated by Registration System")
    c.save()

    messagebox.showinfo("Success", f"Admit Card generated:\n{filename}")

# ----------------------- Upload Photo -----------------------
def upload_photo():
    path = filedialog.askopenfilename(filetypes=[("Image Files", "*.png;*.jpg;*.jpeg")])
    if path:
        photo_path.set(path)
        img = Image.open(path)
        img = img.resize((120, 120))
        img_tk = ImageTk.PhotoImage(img)
        photo_label.config(image=img_tk)
        photo_label.image = img_tk

# ----------------------- UI Setup -----------------------
root = tk.Tk()
root.title("🎓 Admit Card Generator")
root.geometry("600x700")
root.config(bg="#e3f2fd")

# Title Section
header = tk.Label(root, text="🎓 Registration & Admit Card Generator", font=("Poppins", 18, "bold"), bg="#1565c0", fg="white", pady=15)
header.pack(fill="x")

# Card-style frame
card = tk.Frame(root, bg="white", bd=0, relief="solid", highlightbackground="#90caf9", highlightthickness=2)
card.place(relx=0.5, rely=0.52, anchor="center", width=480, height=520)

title_lbl = tk.Label(card, text="Fill Student Details", font=("Poppins", 14, "bold"), bg="white", fg="#1565c0")
title_lbl.pack(pady=10)

# Variables
name_var = tk.StringVar()
roll_var = tk.StringVar()
course_var = tk.StringVar()
date_var = tk.StringVar()
center_var = tk.StringVar()
photo_path = tk.StringVar()

# Function to create styled entry
def create_input(label_text, var):
    frame = tk.Frame(card, bg="white")
    frame.pack(pady=8)
    tk.Label(frame, text=label_text, font=("Poppins", 11), bg="white", fg="#0d47a1", width=12, anchor="w").pack(side="left", padx=5)
    entry = tk.Entry(frame, textvariable=var, font=("Poppins", 11), width=30, bd=1, relief="solid", highlightthickness=1, highlightcolor="#42a5f5")
    entry.pack(side="left", padx=5)
    return entry

# Create input fields
create_input("Name", name_var)
create_input("Roll No", roll_var)
create_input("Course", course_var)
create_input("Exam Date", date_var)
create_input("Exam Center", center_var)

# Photo Section
tk.Button(card, text="📸 Upload Photo", command=upload_photo, font=("Poppins", 10, "bold"), bg="#42a5f5", fg="white", width=20, relief="flat", cursor="hand2").pack(pady=10)
photo_label = tk.Label(card, bg="white")
photo_label.pack(pady=5)

# Generate Button
tk.Button(card, text="Generate Admit Card", command=generate_admit_card, font=("Poppins", 12, "bold"), bg="#2e7d32", fg="white", width=22, relief="flat", cursor="hand2").pack(pady=20)

# Footer
footer = tk.Label(root, text="© 2025 Admit Card System | Developed by Sanchit", font=("Poppins", 9), bg="#e3f2fd", fg="#0d47a1")
footer.pack(side="bottom", pady=10)

root.mainloop()
